### ISSUE TITLE
ESM support

### ISSUE THREAD

**Issue by Heartnett** [unjs/unplugin#10]
I'm currently getting this error when building my ESM project:

> failed to load config from ......./vite.config.ts
> error when starting dev server:
> ReferenceError: __dirname is not defined in ES module scope
> This file is being treated as an ES module because it has a '.js' file extension and '......./package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
>       at file:///......./node_modules/.pnpm/unplugin@0.2.4_vite@2.5.1/node_modules/unplugin/dist/index.mjs:226:40
>       at ModuleJob.run (internal/modules/esm/module_job.js:170:25)
>       at async Loader.import (internal/modules/esm/loader.js:178:24)
>       at async loadConfigFromFile (.......\node_modules\.pnpm\vite@2.5.1\node_modules\vite\dist\node\chunks\dep-972722fa.js:75819:31)
>       at async resolveConfig (.......\node_modules\.pnpm\vite@2.5.1\node_modules\vite\dist\node\chunks\dep-972722fa.js:75434:28)
>       at async createServer (.......\node_modules\.pnpm\vite@2.5.1\node_modules\vite\dist\node\chunks\dep-972722fa.js:73957:20)
>       at async CAC.<anonymous> (.......\node_modules\.pnpm\vite@2.5.1\node_modules\vite\dist\node\cli.js:13963:24)

**Comment by Heartnett** [comment]
@antfu Thank you so much for the quick fix!

Unfortunately I'm now facing a new error:

> failed to load config from .....\vite.config.ts
> error when starting dev server:
> TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of URL. Received undefined
>     at fileURLToPath (internal/url.js:1379:11)
>     at file:///...../node_modules/.pnpm/unplugin@0.2.5_vite@2.5.1/node_modules/unplugin/dist/index.mjs:228:79
>     at ModuleJob.run (internal/modules/esm/module_job.js:170:25)
>     at async Loader.import (internal/modules/esm/loader.js:178:24)
>     at async loadConfigFromFile (.....\node_modules\.pnpm\vite@2.5.1\node_modules\vite\dist\node\chunks\dep-972722fa.js:75819:31)
>     at async resolveConfig (.....\node_modules\.pnpm\vite@2.5.1\node_modules\vite\dist\node\chunks\dep-972722fa.js:75434:28)     
>     at async createServer (.....\node_modules\.pnpm\vite@2.5.1\node_modules\vite\dist\node\chunks\dep-972722fa.js:73957:20)      
>     at async CAC.<anonymous> (.....\node_modules\.pnpm\vite@2.5.1\node_modules\vite\dist\node\cli.js:13963:24)
>  ERROR  Command failed with exit code 1.

**Comment by souljorje** [comment]
@antfu can u please make a release with latest fix? and also update unplugin in https://github.com/antfu/unplugin-vue-components
