### ISSUE TITLE
Advice on processing external imports

### ISSUE THREAD

**Issue by TropicalRaisel** [unjs/unplugin#11]
I'm currently doing this: https://github.com/TropicalRaisel/unplugin-skypin/blob/main/src/index.ts

Which works as expected, however when using `rollup` for example get errors like this:
```javascript
[!] Error: Could not load https://cdn.skypack.dev/pin/hueman@v2.1.3-5b8y8npx5feiJPqgqL57/mode=imports,min/optimized/hueman.js (imported by src/index.js): ENOENT: no such file or directory, open {url but on a file path}
```
How can I avoid having it trying to open a filepath? Configuring `hueman` as an `external` in the `rollup` config just ignores applying the plugin.

**Comment by TropicalRaisel** [comment]
For reference, `rollup-plugin-skypin` returns an object that contains an `external` option, which I'm guessing just tells `rollup` to not look at a file location: https://github.com/MarshallCB/rollup-plugin-skypin/blob/main/src/index.ts#L29

**Comment by antfu** [comment]
Seems like you are using unplugin-starter, in that case, it uses `tsup` to bundle. To external deps, just install them as "dependencies" or "peerDependencies". See https://tsup.egoist.sh/#excluding-packages

**Comment by TropicalRaisel** [comment]
No this isn't for the project itself, it's when *using* the project in `rollup`. I've created a demo for what I mean here: https://github.com/TropicalRaisel/unplugin-skypin-demo

**Comment by TropicalRaisel** [comment]
If you run `yarn rollup -c` you'll get the error above.
