### ISSUE TITLE
Webpack build is broken in unplugin `0.9.0`

### ISSUE THREAD

**Issue by sxzz** [unjs/unplugin#152]
You can see the log from https://github.com/sxzz/unplugin-vue/runs/7743896403?check_suite_focus=true

I have no idea with webpack.

Reproduction repo: https://github.com/sxzz/unplugin-vue/tree/04bc55cb77270930cef981a63cf493dc1cae3d68

Run `pnpm run build` in root workspace, then run `pnpm run build` in `examples/webpack`

It works in `0.8.1`.

**Comment by antfu** [comment]
It would be great if you can narrow down the issue and provide a minimal reproduction (or better as a PR of failing tests)

**Comment by sxzz** [comment]
Of course, I'm traveling now. I create this issue for reminding myself. I'll provide more info when I get back! 😛

**Comment by antfu** [comment]
I guess this might be the case: 
https://github.com/unocss/unocss/commit/d53a3654f320c7a7498ed3379e70dc5bea08418d

**Comment by cjpearson** [comment]
I'm also running into this issue. I don't yet have a minimal reproduction, but it seems to be related to the HtmlWebpackPlugin. I can work around it by adding the following to package.json.

```
"overrides": {
    "unplugin-icons": {
         "unplugin": "0.8.1"
    }
},
```

**Comment by cjpearson** [comment]
Here's a simple reproduction: [unplugin-issue.zip](https://github.com/unjs/unplugin/files/9505017/unplugin-issue.zip)
