### ISSUE TITLE
Typo: SourceMap or SourceMapInput ?

### ISSUE THREAD

**Issue by yfwz100** [unjs/unplugin#160]
Comparing with native Rollup types, it seems that the type annotation of source map in `TransformResult` should be SourceMapInput so the two additional methods in source map is not required.

**Comment by antfu** [comment]
Can you share more details?

**Comment by yfwz100** [comment]
Like 

https://github.com/yfwz100/unplugin-peggy/blob/89b3aa4126bfa69b2da46d9c42a2e91d572312ce/src/plugin.ts#L56

The source map generated by mozilla's source-map lib is incompatible with unplugin's `SourceMap`.

**Comment by yfwz100** [comment]
More details here:

The definition of SourceMap:

https://github.com/rollup/rollup/blob/eb1fab7883846e16af1d8c650715e725a20a2665/src/rollup/types.d.ts#L75-L84

```ts
export interface SourceMap {
	file: string;
	mappings: string;
	names: string[];
	sources: string[];
	sourcesContent: string[];
	version: number;
	toString(): string;
	toUrl(): string;
}
```

The definition of SourceMapInput:

https://github.com/rollup/rollup/blob/eb1fab7883846e16af1d8c650715e725a20a2665/src/rollup/types.d.ts#L86

```ts
export type SourceMapInput = ExistingRawSourceMap | string | null | { mappings: '' };

export interface ExistingRawSourceMap {
	file?: string;
	mappings: string;
	names: string[];
	sourceRoot?: string;
	sources: string[];
	sourcesContent?: string[];
	version: number;
}
```

I don't know if `toString()` and `toUrl()` are required in TransformResult or not. But it's not required in rollup at least.

**Comment by antfu** [comment]
Yeah I see. PR welcome
