### ISSUE TITLE
Remove `vite` and `webpack` as peer dpeendencies

### ISSUE THREAD

**Issue by pi0** [unjs/unplugin#170]
Taking into account unplugin dist has no direct import from `vite` and `webpack`, we shall remove them from `peerDependencies`. Meta frameworks like Nuxt do not need them and it causes issues

<img width="402" alt="image" src="https://user-images.githubusercontent.com/5158436/191189012-4905fa87-8509-4a92-99f9-708316d316d3.png">

**Comment by antfu** [comment]
Makes sense, I have removed all peerDeps in 0.9.6
