### ISSUE TITLE
Rollup 3 support

### ISSUE THREAD

**Issue by lllopo** [unjs/unplugin#181]
I have a project with a module depending on unplugin and I'm getting the following since I've updated to Rollup 3 : 

 @intlify/unplugin-vue-i18n 0.7.0
  └─┬ unplugin 0.8.1
       └── ✕ unmet peer rollup@^2.50.0: found 3.2.3

All other modules I have already updated to support Rollup 3, so please, can you also do something about it.

**Comment by antfu** [comment]
It's already supported, they should upgrade their unplugin.
