### ISSUE TITLE
clarify: what is unplugin

### ISSUE THREAD

**Issue by milahu** [unjs/unplugin#200]
at first sight, its unclear: what is unplugin?

im missing a slogan, something like

> write one plugin for many bundlers

similar to [mitosis](https://github.com/builderio/mitosis)

> Write components once, run everywhere. Compiles to Vue, React, Solid, Angular, Svelte, and more.

similar to [java](https://en.wikipedia.org/wiki/Write_once,_run_anywhere)

> Write once, run anywhere

**Comment by antfu** [comment]
> Unified plugin system

I am not sure what else would you expected.
