### ISSUE TITLE
Feature: Snowpack compatibility

### ISSUE THREAD

**Issue by tropicalraisel** [unjs/unplugin#22]
Snowpack is built using Rollup, and even offers the ability to pass [Rollup options in its config file](https://www.snowpack.dev/reference/configuration), similar to Vite.
Its [plugin API](https://www.snowpack.dev/reference/plugins) is good too.

**Comment by antfu** [comment]
The API looks like Rollup, but actually not very compatible (no `resolveId`, transformResult use `contents` instead of `code`, etc.) We will need to do a compatible layer for it. PR welcome if you managed to make it work at least for transform. Thansk.

**Comment by TropicalRaisel** [comment]
Snowpack does allow direct Rollup configuration through `packageOptions`, and Unplugins can be registered already using `packageOptions.rollup.plugins`. This is why I'm thinking full compatibility shouldn't be too hard.

**Comment by antfu** [comment]
https://dev.to/fredkschott/5-more-things-i-learned-building-snowpack-to-20-000-stars-5dc9

Snowpack is planning to wind down - so I think we could skip the support for it then.

**Comment by tropicalraisel** [comment]
RIP 🪦
