### ISSUE TITLE
Finish Nuxt support

### ISSUE THREAD

**Issue by TropicalRaisel** [unjs/unplugin#23]
I'm in the process of making Nuxt tests for my plugin, and noticed that the base project does not have full Nuxt support yet.
There seems to be some work on a branch and am curious if that is ready to launch: https://github.com/unjs/unplugin/tree/feat/nuxt
If not it would be best to remove compatibility listings in the project docs.

**Comment by antfu** [comment]
We kinda leave it on purpose, see #4. The main idea is that Nuxt modules are capable to handle more (for optimizing, or more functionality), it would be better to have the plugin authors write the nuxt module using the `unplugin` foundation if needed.

> If not it would be best to remove compatibility listings in the project docs.

I don't see we mention it anywhere.

**Comment by TropicalRaisel** [comment]
In the README you list Nuxt as a viable place to include Unplugins, so my assumption is that something like this:
```javascript
export default {
  generate: {
    dir: 'dist/nuxt',
  },
  modules: [['unplugin-skypin/nuxt', { /* options */ }]],
}
```
Is perfectly fine. How would making a Nuxt module using an Unplugin foundation be done?
