### ISSUE TITLE
Import Webpack Unplugins like normal Webpack plugins

### ISSUE THREAD

**Issue by TropicalRaisel** [unjs/unplugin#24]
It would be most intuitive to import unplugins in Webpack like so:
```javascript
const { UnpluginStarterPlugin } = require('unplugin-starter/webpack)

module.exports = {
  plugins: {
    new UnpluginStarterPlugin({ options })
  }
}
```
Or something similar. I'm also still having troubles getting Webpack compatibility to even work at all.

**Comment by antfu** [comment]
You don't need the `new` keyword, we are returning a factory function instead of a class

**Comment by TropicalRaisel** [comment]
@antfu I'm aware, but every time I try to import the plugin the program crashes. I've done the following import using Webpack Encore:
```
Encore.addPlugin(require('unplugin-skypin/webpack'))
```
And finally have a new error:
```
[webpack-cli] Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration.plugins[8] misses the property 'apply'. Should be:
   function
   -> The run point of the plugin, required method.
```

**Comment by antfu** [comment]
Try `require('unplugin-skypin/webpack').default`

**Comment by TropicalRaisel** [comment]
Ok that finally seems to be working lol

May want to update the docs about that
