### ISSUE TITLE
vue-cli use plugin is error

### ISSUE THREAD

**Issue by wojiaoxiaomayun** [unjs/unplugin#286]
### Environment

node version:14.21.3
vue-cli-service:4.5.13
I upgraded to the highest version（16....），but this still not
If you need more information, please contact me

### Reproduction

this is my plugin
[@zkwq/unplugin-color-change](https://www.npmjs.com/package/@zkwq/unplugin-color-change)

### Describe the bug

run code 99%,webpack error,I did't get other error info.
* -!../node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"node_modules/.cache/vue-loader","cacheIdentifier":"500d5e3f-vue-loader-template"}!../node_modules/.store/unplugin@1.3.0/node_modules/unplugin/dist/webpack/loaders/transform.js??unplugin-color-change!../node_modules/cache-loader/dist/cjs.js??ref--12-0!../node_modules/babel-loader/lib/index.js!../node_modules/vue-loader/lib/loaders/templateLoader.js??ref--7!../node_modules/cache-loader/dist/cjs.js??ref--0-0!../node_modules/vue-loader/lib/index.js??vue-loader-options!./App.vue?vue&type=template&id=7ba5bd90& in ./src/App.vue?vue&type=template&id=7ba5bd90&

### Additional context

vue.config.js
const {webpackPlugin,BaseUIColors} = require('@zkwq/unplugin-color-change');
plugins: [
    webpackPlugin({
        [BaseUIColors.primary]:{
            color:'red'
        }
    })
]

**Comment by sxzz** [comment]
Fixed via 166ef6f57527509e904f26c6c8ae9fe0722becbb
Please wait for the next release.
