### ISSUE TITLE
Add options hook

### ISSUE THREAD

**Issue by xiankq** [unjs/unplugin#318]
### Describe the feature

rollup: [https://rollupjs.org/plugin-development/#options](url)
vite: [https://vitejs.dev/guide/api-plugin.html#vite-specific-hooks](url)  `options` and `config`
esbuid: [https://esbuild.github.io/plugins/#build-options](url)
webpack/rspack: It seems that calling the get options before `make` will do.

As for the difference in options, I think developers can judge the meta by themselves.

Please correct, If the Feature Request is reasonable, I am willing to PR.

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by antfu** [comment]
I honestly feel that might not be very useful as the options are very different across the build tools, which losing the point of being universal. We already provide the escape hatches for tools-specific hooks, I think it's not blocking. Thanks for bringing this up.
