### ISSUE TITLE
[Feature Request]: farm plugin support

### ISSUE THREAD

**Issue by ErKeLost** [unjs/unplugin#340]
### Describe the feature

[github farm](https://github.com/farm-fe/farm)

[Farm Core Architecture Design js plugin](https://github.com/farm-fe/rfcs/blob/main/rfcs/001-core-architecture/rfc.md#62-js-plugin)

The farm plugin are inspired by rollup, So this might be straightforward to implement. I also tried to transplant to unplugin to implement all the hooks. With your permission, I'd like to do it.

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by sxzz** [comment]
LGTM. WDYT? @antfu
