### ISSUE TITLE
watchChange is not work in vite。

### ISSUE THREAD

**Issue by yuanlin1995** [unjs/unplugin#348]
### Environment

Unplugin： 1.5.0

### Reproduction

-

### Describe the bug

watchChange is not work in vite。

config: 

{
    name: 'unplugin-gen',
    transform (code, id) {
       // work
    },
    watchChange (id, { event }) {
       // not work
    }
}

**Comment by sxzz** [comment]
Given the timing of the issue, you might want to check https://github.com/vitejs/vite/issues/14823.

For further updates, please provide a minimal reproduction.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)
