### ISSUE TITLE
_unplugin@1.8.0 bug

### ISSUE THREAD

**Issue by yanlveming** [unjs/unplugin#366]
### Environment

npm -v 6.14.17
node 14

### Reproduction

_unplugin@1.8.0@unplugin/dist/index.js:1021   loader.option ||= _options           is Unexpected token '||='

### Describe the bug

![微信图片_20240305114549](https://github.com/unjs/unplugin/assets/40557845/c3ab5c7f-f9a8-4cc5-819f-f2628b73cc13)

**Comment by antfu** [comment]
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by antfu** [comment]
fixed in https://github.com/unjs/unplugin/pull/365

**Comment by OnArrow** [comment]
good camera
