### ISSUE TITLE
The `buildEnd` hook will stuck in 98% when as nuxt `buildModules`

### ISSUE THREAD

**Issue by 2nthony** [unjs/unplugin#37]
```console
● Client █████████████████████████ after emitting (98%)

✔ Server
  Compiled successfully in 3.09s
```

It looks like because of `compiler.hooks.done.tapAsync` as `buildEnd` hook, these hooks below is working normally(that's what I use for now):

```js
webpack(compiler) {
  compiler.hooks.done.tap(pluginname, () => {
    return fs.writeFile()
  })
  // or
  compiler.hooks.done.tapPromise()
}
```

I didn't read the nuxt source code to figure the reason yet.

**Comment by antfu** [comment]
Ah, it's confusing that `tapAsync` is not that `async` 😅. I think we could change it to `tapPromise`, do you mind sending a quick PR? Thanks.
