### ISSUE TITLE
Question regarding support for Deno

### ISSUE THREAD

**Issue by AlexJeffcott** [unjs/unplugin#372]
### Describe the feature

First off, thank you for doing this work - a unified plugins de facto would make the lives of many developers much better, I think.

As far as I can tell, unplugin does not support with Deno, which seems like a shame.

Are there plans to support Deno in the future?

### Additional information

- [x] Would you be willing to help implement this feature?

**Comment by antfu** [comment]
What do you expect by "support Deno"? Does Deno have a similar plugin system?

**Comment by sxzz** [comment]
Since there has been no new information on this issue for a long time, I closed it. If you still have questions, please open a new issue.
