### ISSUE TITLE
Naming convention - unplugin-** prefix? 

### ISSUE THREAD

**Issue by TechAkayy** [unjs/unplugin#40]
webpack official plugins have been using **-webpack-plugin suffix (https://github.com/webpack/webpack/issues/1847)
vite & rollup are using vite-plugin-** and rollup-plugin-** prefixes (https://vitejs.dev/guide/api-plugin.html#conventions)

Looking at the examples (https://github.com/unjs/unplugin#examples), are we sticking with unplugin-** prefixing naming convention? 

But the usage examples (https://github.com/unjs/unplugin#usage) follow suffixes like my-unplugin/ MyUnplugin / my-first-unplugin

**Comment by antfu** [comment]
Yeah, that's a good point. We should stick with prefixing (was trying to make it more grammatical readable in the examples), it make senses to align with the conversion, PR welcome, thanks!
