### ISSUE TITLE
webpack为什么导出的default才是插件方法，不可以直接导出插件方法吗

### ISSUE THREAD

**Issue by Vgbire** [unjs/unplugin#400]
### Describe the feature

我用unjs写的webpack插件，使用的时候需要require('xxx').default()才能使用，我希望const x = require('xxx'), plugin: [x()]。
而不是plugin: [x.default()]

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by sxzz** [comment]
It depends on which bundler you use, refer to https://tsup.egoist.dev/#interop-with-commonjs
