### ISSUE TITLE
Make `webpack-sources` an optional peer dependency

### ISSUE THREAD

**Issue by benmccann** [unjs/unplugin#410]
### Describe the feature

`webpack-sources` is a dependency of this project and is pulled in whether or not you are using `webpack`. It is also a dependency of `webpack`, so I believe it could be made an optional peer dependency here

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by danielroe** [comment]
This breaks new Nuxt installs (and any other use of `unplugin`) as this is now imported directly into the main entrypoint of `unplugin`:

https://unpkg.com/browse/unplugin@1.13.0/dist/index.mjs
