### ISSUE TITLE
missing import `webpack-sources`

### ISSUE THREAD

**Issue by danielroe** [unjs/unplugin#413]
Resolution to https://github.com/unjs/unplugin/issues/410 breaks new Nuxt installs (and any other use of `unplugin` without webpack) as `webpack-sources` is now imported directly into the main entrypoint of `unplugin`.

https://unpkg.com/browse/unplugin@1.13.0/dist/index.mjs

Maybe we could use a dynamic import?

**Comment by danielroe** [comment]
~> https://github.com/unjs/unplugin/issues/412

**Comment by antfu** [comment]
Should be fixed in v1.13.1 with 6d4d2b13277e3904419d8b8227c6336930b9a2ad
