### ISSUE TITLE
args.suffix is ​​undefined when esbuild's onTransform hook is triggered

### ISSUE THREAD

**Issue by KID-joker** [unjs/unplugin#427]
### Environment

unplugin@1.14.1

### Reproduction

[repo](https://github.com/ajuner/super-dev)

And add any unplugin-related plugins.

### Describe the bug

![image](https://github.com/user-attachments/assets/20556f91-aac4-47bf-8df8-e7844dd31dbd)

![image](https://github.com/user-attachments/assets/a4c492a0-3dc8-4538-bc55-7446f3b84e1c)

**Comment by sxzz** [comment]
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example). Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by KID-joker** [comment]
> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example). Thanks.
> 
> > [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

Step 1, download [super-dev](https://github.com/ajuner/super-dev);
Step 2, install `unplugin-auto-import` and use it;
Step 3, `npm run prod`;

Then in [049f99c](https://github.com/evanw/esbuild/commit/049f99c9b578d845a61ed70e1aa02683e46c94ec), we can find that esbuild only provides `args.suffix` from v0.14.3. The esbuild version used in [super-dev](https://github.com/ajuner/super-dev) is v0.12.24.

**Comment by sxzz** [comment]
I guess you can try to upgrade esbuild version, and the issue will be fixed, right?
