### ISSUE TITLE
Add support for watch mode

### ISSUE THREAD

**Issue by jwr12135** [unjs/unplugin#53]
From what I can tell, unplugin does not currently support watch mode features. This should add support for [`closeWatcher`](https://rollupjs.org/guide/en/#closewatcher), [`watchChange`](https://rollupjs.org/guide/en/#watchchange), [`this.addWatchFile`](https://rollupjs.org/guide/en/#thisaddwatchfile), and [`this.getWatchFiles`](https://rollupjs.org/guide/en/#thisgetwatchfiles). I can create a pull request if needed.

**Comment by antfu** [comment]
> I can create a pull request if needed.

That would be great, thanks!
