### ISSUE TITLE
Is it possible to lazy load dependencies?

### ISSUE THREAD

**Issue by pd4d10** [unjs/unplugin#59]
For example, if it's used in Vite or Rollup, these deps should not be loaded.

https://github.com/unjs/unplugin/blob/85a7ce6b1c89972ebf047055cbd0798eadd39656/package.json#L31-L35

**Comment by pd4d10** [comment]
If the API should be kept as is, it seems that the only way is to use the old-style `require()` to lazy load modules here (synchronously):

https://github.com/unjs/unplugin/blob/85a7ce6b1c89972ebf047055cbd0798eadd39656/src/define.ts#L11-L22

**Comment by antfu** [comment]
You can use `buildStart` hook, or basically every hook you want to ensure the async import been resolved.

**Comment by pd4d10** [comment]
Maybe I didn't make it clear, I mean the dependencies of `unplugin` itself.

For example, how about the refactor as follows? The benefit is to avoid Webpack related modules load if it is not called.

```js
export function createUnplugin (factory) {
  return {
    // ...
    get webpack () {
      const { getWebpackPlugin } = require('./webpack')
      return getWebpackPlugin(factory)
    },
    // ...
  }
}
```
