### ISSUE TITLE
webpack issue on `backSlash` on non Windows OS

### ISSUE THREAD

**Issue by userquin** [unjs/unplugin#83]
This [utils.ts](https://github.com/unjs/unplugin/blob/main/src/webpack/utils.ts) should be something like this (for context check https://github.com/unocss/unocss/issues/931):

```ts
import { sep } from 'path'

export function slash (path: string) {
  return path1.replace(/\\/g, '/')
}

export function backSlash (path: string) {
  return path.replace(/[\\/]/g, sep)
}
```

@aliuq

**Comment by aliuq** [comment]
Why not let the slash be consistent with the system's

**Comment by userquin** [comment]
check this comment: https://github.com/unjs/unplugin/blob/main/src/webpack/index.ts#L106

**Comment by aliuq** [comment]
> @aliuq check this comment: https://github.com/unjs/unplugin/blob/main/src/webpack/index.ts#L106

Sorry, I don't understand what this path separator has to do with
